name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # pour utiliser Node 24, et plus Node 20

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3 # Surveiller car utilise Node 20 => passage a Node 24 en Septembre 2026 sur Github
        with:
          terraform_version: 1.15.7
          terraform_wrapper: false   # laisse `terraform -chdir`/version -json intacts

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck bats
          pip install --quiet checkov

      - name: Static — terraform fmt
        run: make fmt

      - name: Static — terraform validate (6 stacks)
        run: make validate

      - name: Static — shellcheck + bash -n
        run: make lint

      - name: Unit — bats (dispatcher + bootstrap)
        run: make unit

      - name: Plan mocké — terraform test
        run: make tftest

      - name: Sécurité — checkov
        run: make sec
